# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurando Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalando Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Primer Lint con Pylint
      run: |
       #Falla la integración si la puntuación es menor que 10
       pylint --fail-under=10 src
    - name: Primer test con PyTest
      run: |
        pytest
